"""Versioned, model-independent contracts for H-CAM analytics metadata."""

from hcam.analytics.contracts import (
    ANALYTICS_EVENT_MODELS,
    MAX_EVENT_BYTES,
    AnalyticEventCreatedV1,
    AnalyticsAssignmentV1,
    AnalyticsContractSafetyError,
    ModelDeploymentChangedV1,
    ObservationCreatedV1,
    TrackUpdatedV1,
    analytics_contract_bundle,
    canonical_contract_json,
    parse_analytics_assignment,
    parse_analytics_event,
)
from hcam.analytics.geometry import (
    GeometryDefinitionV1,
    GeometryScheduleV1,
    LineGeometryV1,
    NormalizedPoint,
    ZoneGeometryV1,
)
from hcam.analytics.runtime import (
    AnalyticsRuntimeAdapter,
    GuardedAnalyticsRuntimeAdapter,
    RuntimeAdapterDescriptorV1,
    RuntimeBatchRequestV1,
    RuntimeBatchRequestV2,
    RuntimeBatchResultV1,
    UnavailableAnalyticsRuntimeAdapter,
    failed_runtime_result,
    validate_runtime_result,
)
from hcam.analytics.taxonomy import TaxonomyClassV1, TaxonomyManifestV1

__all__ = [
    "ANALYTICS_EVENT_MODELS",
    "MAX_EVENT_BYTES",
    "AnalyticEventCreatedV1",
    "AnalyticsAssignmentV1",
    "AnalyticsContractSafetyError",
    "AnalyticsRuntimeAdapter",
    "GeometryDefinitionV1",
    "GeometryScheduleV1",
    "GuardedAnalyticsRuntimeAdapter",
    "LineGeometryV1",
    "ModelDeploymentChangedV1",
    "ObservationCreatedV1",
    "NormalizedPoint",
    "RuntimeAdapterDescriptorV1",
    "RuntimeBatchRequestV1",
    "RuntimeBatchRequestV2",
    "RuntimeBatchResultV1",
    "TaxonomyClassV1",
    "TaxonomyManifestV1",
    "TrackUpdatedV1",
    "UnavailableAnalyticsRuntimeAdapter",
    "ZoneGeometryV1",
    "analytics_contract_bundle",
    "canonical_contract_json",
    "failed_runtime_result",
    "parse_analytics_assignment",
    "parse_analytics_event",
    "validate_runtime_result",
]
