export const p54UnavailableProducers = [
  "hypothesis_list_api",
  "hypothesis_detail_api",
  "correlation_run_api",
  "relationship_api",
  "spatial_api",
  "rule_trace_api",
  "candidate_api",
  "proposed_alert_api",
  "review_policy_api",
  "review_command_api",
  "review_receipt_api",
  "correction_api",
  "event_stream",
  "department_scope_api",
  "capability_api",
  "freshness_api",
  "pagination_api",
  "concurrency_api",
  "idempotency_api",
  "quorum_api",
  "calibration_api",
  "provenance_api",
  "investigation_handoff_api",
  "gis_handoff_api",
  "command_summary_api",
  "health_api",
] as const;
export const p54Threats = Array.from(
  { length: 40 },
  (_, index) => `P5.4-T${String(index + 1).padStart(2, "0")}` as const,
);
